<form id="pagerForm" method="post" action="/alog">
    <input type="hidden" name="user_name" value="" />
    <input type="hidden" name="pageNum" value="1" />
    <input type="hidden" name="numPerPage" value="<?=$this->rolelist['numPerPage']?>" />
    <input type="hidden" name="orderField" value="" />
</form>
<div class="pageHeader">
    <form onsubmit="return navTabSearch(this);"  action="/alog" method="post">
        <div class="searchBar">
            <table class="searchContent">
                <tr>
                    <td>
                       
                    </td>
                    <td>
                       姓名：<input type="text" name="user_name" value="<?=$this->role_name?>"/>
                    </td>
                    <td>
                        <div class="buttonActive"><div class="buttonContent"><button type="submit">检索</button></div></div>
                    </td>
                </tr>
            </table>
        </div>
    </form>
</div>
<div class="pageContent">
    <table class="table" width="100%" layoutH="89">
        <thead>
            <tr>
                <th width="60" align="center">ID</th>
                <th width="60" align="center">user_id</th>
                <th width="80" align="center">姓名</th>
                <th align="center">操作日志</th>
                <th width="80" align="center">op</th>
                <th width="80" align="center">操作时间</th>
                <th width="80" align="center">浏览</th
            </tr>
        </thead>
        <tbody>
            <?php if(!empty($this->loglist['list'])): ?>
            <?php foreach($this->loglist['list'] as $key=>$val): ?>
            <tr target="sid_user" rel="<?php echo $this->escape($val['id']);?>">
                <td><?php echo $this->escape($val['id']);?></td>
                <td><?php echo $this->escape($val['user_id']);?></td>
                <td><?php echo $this->escape($val['username']);?></td>
                <td><?php echo mb_substr($val['log'], 0, 80, 'UTF-8');?></td>
                <td><?php echo $this->escape($val['opname']);?></td>
                <td><?php echo $this->escape($val['datetime']);?></td>
                <td><a href='/alog/show?logid=<?php echo $this->escape($val['id']);?>'  ask="true"  target="dialog"  rel="look_alog"title="查看LOG详情" width="800" height="480"  >查看</a></td>
            </tr>
            <?php endforeach;?>
            <?php endif; ?>

        </tbody>
    </table>
    <div class="panelBar">
        <div class="pages">
            <span>显示</span>
            <select class="combox" name="numPerPage" onchange="navTabPageBreak({numPerPage: this.value})">
                <option value="20" <?php if ($this->loglist['numPerPage'] == 20): ?>selected<?php endif; ?> >20</option>
                <option value="50" <?php if ($this->loglist['numPerPage'] == 50): ?>selected<?php endif; ?>>50</option>
                <option value="100" <?php if ($this->loglist['numPerPage'] == 100): ?>selected<?php endif; ?>>100</option>
            </select>
            <span>条，共<?=$this->loglist['totalCount']?>条</span>
        </div>
        <div class="pagination" targetType="navTab" totalCount="<?=$this->loglist['totalCount']?>" numPerPage="<?=$this->loglist['numPerPage']?>" pageNumShown="10" currentPage="<?=$this->loglist['currentPage']?>"></div>
    </div>
</div>
