<form id="pagerForm" method="post" action="/user">
    <input type="hidden" name="user_id" value="" class="digits">
    <input type="hidden" name="user_name" value="" />
    <input type="hidden" name="pageNum" value="1" />
    <input type="hidden" name="numPerPage" value="<?=$this->userlist['numPerPage']?>" />
    <input type="hidden" name="orderField" value="" />
</form>

<div class="pageHeader">
    <form onsubmit="return navTabSearch(this);"  action="/user" method="post">
        <div class="searchBar">
            <table class="searchContent">
                <tr>
                    <td>
                        Id：<input type="text" name="user_id" class="digits" value="<?=$this->user_id?>"/>
                    </td>
                    <td>
                        真实姓名：<input type="text" name="user_name" value="<?=$this->user_name?>"/>
                    </td>
                    <td>
                        <div class="buttonActive"><div class="buttonContent"><button type="submit">检索</button></div></div>
                    </td>
                </tr>
            </table>
        </div>
    </form>
</div>
<div class="pageContent">
    <div class="panelBar">
        <ul class="toolBar" style="float: right;">
            <li><a class="add" href="/user/add" target="navTab" title="添加用户"><span>添加</span></a></li>
            <li><a class="edit" href="/user/update?user_id={sid_user}" target="navTab"  title="编辑用户"><span>修改</span></a></li>
            <li class="line">line</li>
            <li><a class="icon" href="/user/excel" target="dwzExport" targetType="navTab" title="确定要导出这些记录吗?"><span>导出EXCEL</span></a></li>
            <li class="line">line</li>
            <li><a class="edit" href="/Userexcel/index" target="dwzExport" targetType="navTab" title="确定要导出这些记录吗?"><span>导出用户权限list</span></a></li>
            <li class="line">line</li>
            <li><a class="delete" href="/user/del?user_id={sid_user}" target="ajaxTodo" title="确定要删除吗?"><span>删除</span></a></li>
        </ul>
    </div>
    <table class="table" width="100%" layoutH="115">
        <thead>
            <tr>
                <th width="80" align="center">ID</th>
                <th width="120" align="center">用户名</th>
                <th align="center">真实姓名</th>
                <th width="100" align="center">电话</th>
                <th width="350" align="center">邮箱</th>
                <th width="100" align="center">用户类别</th>
                <th width="200" align="center">更新时间</th>
            </tr>
        </thead>
        <tbody>
            <?php if(!empty($this->userlist['list'])): ?>
            <?php foreach($this->userlist['list'] as $key=>$val): ?>
            <tr target="sid_user" rel="<?php echo $this->escape($val['user_id']);?>">
                <td><?php echo $this->escape($val['user_id']);?></td>
                <td><?php echo $this->escape($val['user_name']);?></td>
                <td><?php echo $this->escape($val['user_realname']);?></td>
                <td><?php echo $this->escape($val['user_mobile']);?></td>
                <td><?php echo $this->escape($val['user_mail']);?></td>
                <td><?php if(trim($val['user_type'])==1):?>系统用户<?php elseif(trim($val['user_type'])==2):?>产品管理 <?php elseif(trim($val['user_type'])==3):?>仅管理后台<?php endif;?></td>
                <td><?php echo $this->escape($val['user_cdate']);?></td>
            </tr>
            <?php endforeach;?>
            <?php endif; ?>

        </tbody>
    </table>
    <div class="panelBar">
        <div class="pages">
            <span>显示</span>
            <select class="combox" name="numPerPage" onchange="navTabPageBreak({numPerPage: this.value})">
                <option value="20" <?php if ($this->userlist['numPerPage'] == 20): ?>selected<?php endif; ?> >20</option>
                <option value="50" <?php if ($this->userlist['numPerPage'] == 50): ?>selected<?php endif; ?>>50</option>
                <option value="100" <?php if ($this->userlist['numPerPage'] == 100): ?>selected<?php endif; ?>>100</option>
            </select>
            <span>条，共<?=$this->userlist['totalCount']?>条</span>
        </div>
        <div class="pagination" targetType="navTab" totalCount="<?=$this->userlist['totalCount']?>" numPerPage="<?=$this->userlist['numPerPage']?>" pageNumShown="10" currentPage="<?=$this->userlist['currentPage']?>"></div>
    </div>
</div>
