<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>管理后台</title>

        <link href="/themes/default/style.css" rel="stylesheet" type="text/css" media="screen"/>
        <link href="/themes/css/core.css" rel="stylesheet" type="text/css" media="screen"/>
        <link href="/themes/css/print.css" rel="stylesheet" type="text/css" media="print"/>
        <link href="/uploadify/css/uploadify.css" rel="stylesheet" type="text/css" media="screen"/>
        <!--[if IE]>
        <link href="themes/css/ieHack.css" rel="stylesheet" type="text/css" media="screen"/>
        <![endif]-->

        <!--[if lte IE 9]>
        <script src="/js/speedup.js" type="text/javascript"></script>
        <![endif]-->
        <script src="/js/jquery-1.7.2.js" type="text/javascript"></script>
        <script src="/js/jquery.cookie.js" type="text/javascript"></script>
        <script src="/js/jquery.validate.js" type="text/javascript"></script>
        <script src="/js/jquery.bgiframe.js" type="text/javascript"></script>
        <script src="/xheditor/xheditor-1.2.1.min.js" type="text/javascript"></script>
        <script src="/xheditor/xheditor_lang/zh-cn.js" type="text/javascript"></script>
        <script src="/uploadify/scripts/jquery.uploadify.js" type="text/javascript"></script>

        <!-- svg图表  supports Firefox 3.0+, Safari 3.0+, Chrome 5.0+, Opera 9.5+ and Internet Explorer 6.0+ -->
        <script type="text/javascript" src="/chart/raphael.js"></script>
        <script type="text/javascript" src="/chart/g.raphael.js"></script>
        <script type="text/javascript" src="/chart/g.bar.js"></script>
        <script type="text/javascript" src="/chart/g.line.js"></script>
        <script type="text/javascript" src="/chart/g.pie.js"></script>
        <script type="text/javascript" src="/chart/g.dot.js"></script>

        <script src="/js/dwz.core.js" type="text/javascript"></script>
        <script src="/js/dwz.util.date.js" type="text/javascript"></script>
        <script src="/js/dwz.validate.method.js" type="text/javascript"></script>
        <script src="/js/dwz.barDrag.js" type="text/javascript"></script>
        <script src="/js/dwz.drag.js" type="text/javascript"></script>
        <script src="/js/dwz.tree.js" type="text/javascript"></script>
        <script src="/js/dwz.accordion.js" type="text/javascript"></script>
        <script src="/js/dwz.ui.js" type="text/javascript"></script>
        <script src="/js/dwz.theme.js" type="text/javascript"></script>
        <script src="/js/dwz.switchEnv.js" type="text/javascript"></script>
        <script src="/js/dwz.alertMsg.js" type="text/javascript"></script>
        <script src="/js/dwz.contextmenu.js" type="text/javascript"></script>
        <script src="/js/dwz.navTab.js" type="text/javascript"></script>
        <script src="/js/dwz.tab.js" type="text/javascript"></script>
        <script src="/js/dwz.resize.js" type="text/javascript"></script>
        <script src="/js/dwz.dialog.js" type="text/javascript"></script>
        <script src="/js/dwz.dialogDrag.js" type="text/javascript"></script>
        <script src="/js/dwz.sortDrag.js" type="text/javascript"></script>
        <script src="/js/dwz.cssTable.js" type="text/javascript"></script>
        <script src="/js/dwz.stable.js" type="text/javascript"></script>
        <script src="/js/dwz.taskBar.js" type="text/javascript"></script>
        <script src="/js/dwz.ajax.js" type="text/javascript"></script>
        <script src="/js/dwz.pagination.js" type="text/javascript"></script>
        <script src="/js/dwz.database.js" type="text/javascript"></script>
        <script src="/js/dwz.datepicker.js" type="text/javascript"></script>
        <script src="/js/dwz.effects.js" type="text/javascript"></script>
        <script src="/js/dwz.panel.js" type="text/javascript"></script>
        <script src="/js/dwz.checkbox.js" type="text/javascript"></script>
        <script src="/js/dwz.history.js" type="text/javascript"></script>
        <script src="/js/dwz.combox.js" type="text/javascript"></script>
        <script src="/js/dwz.print.js" type="text/javascript"></script>
        <!--<script src="/bin/dwz.min.js" type="text/javascript"></script>-->
        <script src="/js/dwz.regional.zh.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(function() {
                DWZ.init("/frag_config.xml", {
                    //loginUrl: "login_dialog.html", loginTitle: "登录", // 弹出登录对话框
                    loginUrl: "/member", // 跳到登录页面
                    statusCode: {ok: 200, error: 300, timeout: 301, forbidden:403}, //【可选】
                    pageInfo: {pageNum: "pageNum", numPerPage: "numPerPage", orderField: "orderField", orderDirection: "orderDirection"}, //【可选】
                    debug: false, // 调试模式 【true|false】
                    callback: function() {
                        initEnv();
                        $("#themeList").theme({themeBase: "themes"}); // themeBase 相对于index页面的主题base路径
                    }
                });
                 $.ajaxSettings.global=false; //去掉数据加载
                //$("#sidebar").bind(“contextmenu”,function(){return false;}); 
            });
            function closeEw() {
                //$.pdialog.closeCurrent();
                navTab.closeCurrentTab();
            }
        </script>
    </head>

    <body scroll="no">
        <div id="layout">
            <div id="header">
                <div class="headerNav">
                    <a class="logo" href="/">标志</a>
                    <ul class="nav">
                        <li id="switchEnvBox" style="display:none"><a href="javascript:">（<span>北京</span>）切换城市</a>
                            <ul>
                                <li><a href="sidebar_1.html">北京</a></li>
                                <li><a href="sidebar_2.html">上海</a></li>
                                <li><a href="sidebar_2.html">南京</a></li>
                                <li><a href="sidebar_2.html">深圳</a></li>
                                <li><a href="sidebar_2.html">广州</a></li>
                                <li><a href="sidebar_2.html">天津</a></li>
                                <li><a href="sidebar_2.html">杭州</a></li>
                            </ul>
                        </li>
                        <li style="color:#b9ccda;background: none"><?php echo $this->layout_user_name; ?>&nbsp;&nbsp;</li>
                        <li><a href="/user/passwd" target="navTab" rel="user_passwd">修改密码</a></li>
                        <li><a href="/member/logout" >退出</a></li>
                    </ul>
                    <ul class="themeList" id="themeList">
                        <li theme="default"><div class="selected">蓝色</div></li>
                        <li theme="green"><div>绿色</div></li>
                        <!--<li theme="red"><div>红色</div></li>-->
                        <li theme="purple"><div>紫色</div></li>
                        <li theme="silver"><div>银色</div></li>
                        <li theme="azure"><div>天蓝</div></li>
                    </ul>
                </div>
                <!-- navMenu -->
            </div>

            <div id="leftside">
                <div id="sidebar_s">
                    <div class="collapse">
                        <div class="toggleCollapse"><div></div></div>
                    </div>
                </div>
                <div id="sidebar">
                    <div class="toggleCollapse"><h2>主菜单</h2><div>收缩</div></div>
                    <div class="accordion" fillSpace="sidebar">
                        <?php foreach ($this->menulist as $list): ?>
                            <?php if (!empty($list['sublist'])): ?>
                                <div class="accordionHeader">
                                    <h2><span>Folder</span><?php echo $this->escape($list['title']); ?></h2>
                                </div>
                                <div class="accordionContent">
                                    <ul class="tree treeFolder">
                                        <?php foreach ($list['sublist'] as $key => $val): ?>
                                            <li><a <?php if ($val['href'] !== ''): ?> href="<?= $val['href'] ?>"<?php endif; ?><?php if ($val['target'] !== ''): ?> target="<?= $val['target'] ?>"<?php endif; ?><?php if ($val['rel'] !== ''): ?> rel="<?= $val['rel'] ?>"<?php endif; ?> ><?php echo $this->escape($val['title']); ?></a>
                                                <?php if (isset($val['sublist'])): ?>
                                                    <ul>
                                                        <?php foreach ($val['sublist'] as $subkey => $subval): ?>
                                                            <li><a <?php if ($subval['href'] !== ''): ?> href="<?= $subval['href'] ?>"<?php endif; ?><?php if ($subval['target'] !== ''): ?> target="<?= $subval['target'] ?>"<?php endif; ?><?php if ($subval['rel'] !== ''): ?> rel="<?= $subval['rel'] ?>"<?php endif; ?> <?php if (isset($subval['sublist'])): ?> class="tree" <?php endif; ?>><?php echo $this->escape($subval['title']); ?></a>
                                                                <?php if (isset($subval['sublist'])): ?>
                                                                    <ul>
                                                                        <?php foreach ($subval['sublist'] as $sub2key => $sub2val): ?>
                                                                            <li><a <?php if ($sub2val['href'] !== ''): ?> href="<?= $sub2val['href'] ?>"<?php endif; ?><?php if ($sub2val['target'] !== ''): ?> target="<?= $sub2val['target'] ?>"<?php endif; ?><?php if ($sub2val['rel'] !== ''): ?> rel="<?= $sub2val['rel'] ?>"<?php endif; ?>> <?php echo $this->escape($sub2val['title']); ?></a></li><?php endforeach; ?>
                                                                    </ul>
                                                                <?php endif; ?>
                                                            </li><!-- 显一级 -->
                                                        <?php endforeach; ?>
                                                    </ul>
                                                <?php endif; ?>

                                            </li><!-- 显一级 -->
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div id="container">
                <div id="navTab" class="tabsPage">
                    <div class="tabsPageHeader">
                        <div class="tabsPageHeaderContent"><!-- 显示左右控制时添加 class="tabsPageHeaderMargin" -->
                            <ul class="navTab-tab">
                                <li tabid="main" class="main"><a href="javascript:;"><span><span class="home_icon">我的主页</span></span></a></li>
                            </ul>
                        </div>
                        <div class="tabsLeft">left</div><!-- 禁用只需要添加一个样式 class="tabsLeft tabsLeftDisabled" -->
                        <div class="tabsRight">right</div><!-- 禁用只需要添加一个样式 class="tabsRight tabsRightDisabled" -->
                        <div class="tabsMore">more</div>
                    </div>
                    <ul class="tabsMoreList">
                        <li><a href="javascript:;">我的主页</a></li>
                    </ul>

                    <div class="navTab-panel tabsPageContent layoutBox">

                        <div class="page unitBox">
                            <?php echo $this->layout()->content; ?>
                            <div class="pageFormContent" layoutH="80" style="margin-right:230px;display: none">
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>

        <div id="footer">Copyright &copy; 2012~2017 UE inc.<a href="javascript:;" target="dialog"></a> 京ICP证120206 ICP备1xxxxxx号</div>
        <script type="text/javascript">
            // $("document").bind(“contextmenu”, function(){return false; });
            $(document).ready(function() {
                $("#sidebar").bind("contextmenu", function(e) {
                    return false;
                });
            });
        </script>
    </body>
</html>