<h2 class="contentTitle">后台管理系统</h2>
<div style="margin: 20px">
    <pre style="margin:5px;line-height:1.5em">
<h2>一、关于线上用户开通权限的说明</h2>
■ OP负责为线上用户开通权限
任二:182xxxxxxxx/F6-A109/3859

<h2>二、日常维护联系人</h2>
张三 138xxxxxxxx （游戏管理、合同管理、结算项目、自有平台）
李四 136xxxxxxx/F6-A079 （单机项目、CRM）
王五 136xxxxxxx/F6-A083/3462 （单机项目、客服项目、CRM)

上线流程说明
http://task.uenu.com

上线操作联系人
DBA 晓七 185xxxxxxxx
    </pre>
    <h2>常见问题及解决方案:</h2><br />
    <div class="divider"></div>
    <h2>技术支持(<span style="color:red;">前端组</span>):</h2><br/>
    <pre style="margin:5px;line-height:1.4em;">
    </pre>
</div>